name: DynamicPerformance
version: 1.0.0
main: com.itzlynx197.dynamicperformance.DynamicPerformancePlugin
api-version: 1.21
authors:
  - itz_lynx197
description: An advanced Minecraft server optimization plugin for 1.21.x
softdepend: []

commands:
  dp:
    description: Admin commands for Dynamic PERFORMANCE+
    usage: /dp <subcommand>
    permission: dynamicperformance.admin

permissions:
  dynamicperformance.admin:
    description: Allows access to all Dynamic PERFORMANCE+ commands
    default: op
  dynamicperformance.optimize:
    description: Allows using the one-click optimize command
    default: op